name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t amudhavallir/stay-hub-frontend --build-arg VITE_API_BASE_URL='${{secrets.VITE_API_BASE_URL}}' --build-arg VITE_STRIPE_PUB_KEY="${{secrets.VITE_STRIPE_PUB_KEY}} .
      - name: Publish Image to Docker Hub
        run: docker push amudhavallir/stay-hub-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull amudhavallir/stay-hub-frontend:latest
      - name: Delete old Container
        run: docker rm -f stay-hub-frontend
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name stay-hub-frontend amudhavallir/stay-hub-frontend
